# Generated by Django 4.2.3 on 2024-01-02 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workschedule", "0009_rename_calendarpersonalinfo_surveycalendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForbiddenPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="ダメな組み合わせ（2人選ぶ）"
                    ),
                ),
            ],
        ),
    ]
