# Generated by Django 4.2.3 on 2024-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workschedule", "0010_forbiddenpair"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefinitionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
            ],
        ),
    ]
